version: "3.9"
services:
  backend:
    container_name: backend
    build: ./docker/nestjs/.
    working_dir: /app
    volumes:
      - ./backend:/app
    tty: true
    ports:
      - "3500:3500"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SECRET_HASH: ${SECRET_HASH}
  db:
    container_name: db
    image: mysql:8.0.31
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - volume-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: "exit 0"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/x86_64
    depends_on: 
        - db
    ports: 
    - "8082:80"
    environment: 
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
  frontend:
    container_name: frontend
    build: ./docker/nuxt/.
    working_dir: /nuxt
    volumes:
      - ./frontend:/nuxt
    tty: true
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
      - "24679:24679"
volumes:
  volume-data: